apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argo-cron
spec:
  schedule: "7 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 600 # 10 min
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3300 # 55min
      template:
        spec:
          containers:
            - name: argo-cli
              image: bitphy/argo-cron:latest
              imagePullPolicy: Always
              args: ["nodoambar-hourly-batch.workflow.yaml"]
              tty: true 
              env:
                - name: NAMESPACE
                  value: dev
                - name: OLDER
                  value: 5d
                - name: GIT_BRANCH
                  value: ft/initial-shop-workflows
                - name: GIT_REPO
                  valueFrom:
                    secretKeyRef:
                      name: git-ssh
                      key: git-repo
              volumeMounts:
              - name: git-ssh
                mountPath: "/root/.ssh/"
                readOnly: false
          restartPolicy: Never
          serviceAccountName: default
          volumes:
          - name: git-ssh
            secret:
              secretName: git-ssh
              items: 
              - key: private-key
                path: 'id_rsa'
                mode: 0600
              - key: known-hosts
                path: known_hosts
                mode: 0600
